version: '3.8'

services:
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"   # Puerto para el broker
      - "8080:8080"   # Puerto para la interfaz web
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
    volumes:
      - ./data:/pulsar/data
