version: '3'

services:
  anonimizador:
    build:
      context: .
      dockerfile: anonimizador.Dockerfile
    container_name: anonimizador
    hostname: anonimizador
    restart: on-failure
    ports:
      - "5002:5002"
    networks:
      - app_network

  saludtech:
    build:
      context: .
      dockerfile: saludtech.Dockerfile
    container_name: saludtech
    hostname: saludtech
    restart: on-failure
    ports:
      - "5000:5000"
    networks:
      - app_network

  bff:
    build:
      context: .
      dockerfile: bff.Dockerfile
    container_name: bff
    hostname: bff
    restart: on-failure
    ports:
      - "5050:5050"
    networks:
      - app_network

  tokenizador:
    build:
      context: .
      dockerfile: tokenizador.Dockerfile
    container_name: tokenizador
    hostname: tokenizador
    restart: on-failure
    ports:
      - "5001:5001"
    networks:
      - app_network


  pulsar-express:
    image: bbonnin/pulsar-express
    container_name: pulsar-express
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - SERVICE_URL=http://34.135.143.83:6650
      - REFRESH_INTERVAL=5000  # Actualiza cada 5s para ver cambios más rápido
    restart: on-failure



networks:
  app_network:
    driver: bridge