version: '3'

services:
  anonimizador:
    build:
      context: .
      dockerfile: anonimizador.Dockerfile
    container_name: anonimizador
    hostname: anonimizador
    restart: on-failure
    ports:
      - "5002:5002"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge